"""Parameterize the protein: clean the PDB, build the Amber topology, convert to GROMACS.

Corresponds to ``param_prot.sh``: strip the entry PDB, run pdb4amber, build a minimal
solvation with tleap to obtain solvent templates, convert Amber->GROMACS with ParmEd,
extract single Na+/Cl-/WAT templates, then rebuild the final protein topology.

This is the first step; it downloads ``<PDBID>.pdb`` into the workdir if absent, so it
has no required pre-existing input files.
"""

from __future__ import annotations

import sys
import textwrap
from pathlib import Path

from ...pdb_file_processing import ensure_entry_pdb_file
from ..config import SystemConfig
from ..gmx import checksums, run_tool
from ..results import StepInputs, StepResult, StepStatus

STEP = "param_prot"

_TLEAP_FF = """\
source leaprc.protein.ff19SB
source leaprc.DNA.OL15
source leaprc.RNA.OL3
source leaprc.water.spceb
source leaprc.gaff2
"""


class ParamProtInputs(StepInputs):
    pdb_id: str

    def consumed_paths(self) -> list[Path]:
        return []  # entry PDB is downloaded if missing


class ParamProtResult(StepResult):
    @property
    def prot_top(self) -> Path:
        return self.output("prot_top")

    @property
    def prot_pdb(self) -> Path:
        return self.output("prot_pdb")


def resolve_inputs(workdir: Path, cfg: SystemConfig) -> ParamProtInputs:
    return ParamProtInputs(workdir=Path(workdir), pdb_id=cfg.pdb_id)


def check_inputs(inputs: ParamProtInputs) -> None:
    inputs.check_exists(STEP)


def param_prot(inputs: ParamProtInputs, *, resume: bool = False) -> ParamProtResult:
    check_inputs(inputs)
    wd = inputs.workdir
    wd.mkdir(parents=True, exist_ok=True)

    outputs = {
        "pdb_clean": wd / "pdb_clean.pdb",
        "pdb_clean_amber": wd / "pdb_clean_amber.pdb",
        "prot_parm7": wd / "prot.parm7",
        "prot_rst7": wd / "prot.rst7",
        "prot_top": wd / "prot.top",
        "prot_pdb": wd / "prot.pdb",
        "wat_pdb": wd / "WAT.pdb",
        "na_pdb": wd / "Na+.pdb",
        "cl_pdb": wd / "Cl-.pdb",
    }

    if resume and outputs["prot_top"].exists() and outputs["prot_pdb"].exists():
        return ParamProtResult(
            step=STEP,
            status=StepStatus.SKIPPED,
            workdir=wd,
            outputs=outputs,
            params={"pdb_id": inputs.pdb_id},
        )

    entry_pdb = ensure_entry_pdb_file(inputs.pdb_id, wd)

    _clean_pdb(wd, entry_pdb)
    _tleap(wd, "tleap_temp.in", _initial_solvation_input())
    _amber_to_gromacs(wd)
    _extract_solvent_pdbs(wd)
    _tleap(wd, "tleap_prot.in", _final_topology_input())
    _amber_to_gromacs(wd)

    return ParamProtResult(
        step=STEP,
        status=StepStatus.COMPLETED,
        workdir=wd,
        outputs=outputs,
        params={"pdb_id": inputs.pdb_id},
        input_checksums=checksums({"entry_pdb": entry_pdb}),
    )


def _clean_pdb(workdir: Path, entry_pdb: Path) -> None:
    """Strip REMARK/KEYWDS, keep structural records, then run pdb4amber (--prot)."""
    kept: list[str] = []
    with open(entry_pdb) as fh:
        for line in fh:
            if line.startswith(("REMARK", "KEYWDS")):
                continue
            if line.startswith(("CRYST1", "ATOM", "HETATM", "TER", "END")):
                kept.append(line)
    (workdir / "pdb_clean.pdb").write_text("".join(kept))
    run_tool(
        ["pdb4amber", "-i", "pdb_clean.pdb", "--prot", "-o", "pdb_clean_amber.pdb"],
        tool="pdb4amber",
        cwd=workdir,
        log_path=workdir / "pdb4amber_clean.log",
    )


def _initial_solvation_input() -> str:
    return _TLEAP_FF + textwrap.dedent("""\
        p = loadpdb pdb_clean_amber.pdb
        x = combine{p}
        addions2 x Cl- 0
        addions2 x Na+ 0
        addions2 x Na+ 1
        addions2 x Cl- 1
        solvateBox x SPCBOX 1.
        set default PBradii mbondi3
        set default nocenter on
        saveAmberParm x prot.parm7 prot.rst7
        quit
    """)


def _final_topology_input() -> str:
    return _TLEAP_FF + textwrap.dedent("""\
        p = loadpdb pdb_clean_amber.pdb
        w = loadpdb WAT.pdb
        x = combine{p w}
        addions2 x Na+ 0
        addions2 x Cl- 0
        addions2 x Na+ 1
        addions2 x Cl- 1
        set default PBradii mbondi3
        set default nocenter on
        saveAmberParm x prot.parm7 prot.rst7
        quit
    """)


def _tleap(workdir: Path, script_name: str, tleap_input: str) -> None:
    (workdir / script_name).write_text(tleap_input)
    run_tool(
        ["tleap", "-f", script_name],
        tool="tleap",
        cwd=workdir,
        log_path=workdir / f"{script_name}.log",
    )
    # prot.top/prot.pdb are (re)generated by ParmEd; remove any stale copies first.
    for f in ("prot.top", "prot.pdb"):
        (workdir / f).unlink(missing_ok=True)


def _amber_to_gromacs(workdir: Path) -> None:
    """Convert Amber parm7/rst7 to GROMACS topology + PDB with ParmEd."""
    script = textwrap.dedent("""\
        import parmed as pmd
        parm = pmd.load_file("prot.parm7", "prot.rst7")
        parm.save("prot.top")
        parm.save("prot.pdb")
    """)
    (workdir / "amber_to_gromacs.py").write_text(script)
    run_tool(
        [sys.executable, "amber_to_gromacs.py"],
        tool="parmed (amber->gromacs)",
        cwd=workdir,
        log_path=workdir / "amber_to_gromacs.log",
    )


def _extract_solvent_pdbs(workdir: Path) -> None:
    """Pull single Na+, Cl-, and WAT coordinate templates from the solvated PDB."""
    with open(workdir / "prot.pdb") as fh:
        hetatm = [line for line in fh if line.startswith("HETATM")]

    na = [line for line in hetatm if "Na+" in line]
    cl = [line for line in hetatm if "Cl-" in line]
    wat = [line for line in hetatm if "WAT" in line]
    if na:
        (workdir / "Na+.pdb").write_text(na[0])
    if cl:
        (workdir / "Cl-.pdb").write_text(cl[0])
    if wat:
        (workdir / "WAT.pdb").write_text("".join(wat[:3]))
